/**
 * Shared plumbing for sync-website-chrome.mjs and check-website-chrome-parity.mjs.
 *
 * A "source" is either a local git clone of fe-didit-website-v4 read at a ref
 * (`git show ref:path`, the default - clean regardless of the clone's working
 * tree), or a plain directory (CI checks the website repo out at a ref and
 * reads it from disk).
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

/** Read one file from the source. Returns a Buffer. Throws if missing. */
export function makeReader({ gitDir, ref, dir }) {
  if (dir) {
    return (srcPath) => fs.readFileSync(path.join(dir, srcPath));
  }
  if (!gitDir || !ref) throw new Error("need --from-git <dir> --ref <ref> or --from-dir <dir>");
  return (srcPath) =>
    execFileSync("git", ["-C", gitDir, "show", `${ref}:${srcPath}`], {
      maxBuffer: 64 * 1024 * 1024,
    });
}

/** List every file under a source directory (sorted, repo-relative paths). */
export function makeLister({ gitDir, ref, dir }) {
  if (dir) {
    return (srcDir) => {
      const out = [];
      const walk = (d) => {
        for (const entry of fs.readdirSync(path.join(dir, d), { withFileTypes: true })) {
          const p = `${d}/${entry.name}`;
          if (entry.isDirectory()) walk(p);
          else out.push(p);
        }
      };
      walk(srcDir);
      return out.sort();
    };
  }
  return (srcDir) =>
    execFileSync("git", ["-C", gitDir, "ls-tree", "-r", "--name-only", ref, "--", srcDir], {
      encoding: "utf8",
    })
      .split("\n")
      .filter(Boolean)
      .sort();
}

export function resolveCommit({ gitDir, ref, dir }) {
  if (dir) return null;
  return execFileSync("git", ["-C", gitDir, "rev-parse", ref], { encoding: "utf8" }).trim();
}

/**
 * The one deterministic rewrite applied to vendored .ts/.tsx sources: the
 * website's `@/` path alias becomes `@website/` (mapped to the vendor dir in
 * tsconfig), so vendored imports can never collide with the help centre's own
 * `@/*` alias. Everything else is byte-identical.
 */
export function rewriteImports(text) {
  return text.replaceAll('from "@/', 'from "@website/').replaceAll('import("@/', 'import("@website/');
}

/**
 * Extract the design-token `:root { ... }` block from the website globals.css.
 * The block is the first `:root {` inside the first `@layer base {` and is
 * emitted verbatim (unlayered - the help centre does not use Tailwind layers).
 */
export function extractTokens(globalsCss) {
  const layerIdx = globalsCss.indexOf("@layer base {");
  if (layerIdx === -1) throw new Error("globals.css: '@layer base {' not found");
  const rootIdx = globalsCss.indexOf(":root {", layerIdx);
  if (rootIdx === -1) throw new Error("globals.css: ':root {' not found inside @layer base");
  let depth = 0;
  let end = -1;
  for (let i = globalsCss.indexOf("{", rootIdx); i < globalsCss.length; i++) {
    const ch = globalsCss[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) throw new Error("globals.css: unbalanced :root block");
  // Re-indent from the @layer nesting (4 spaces) to top level (2 spaces).
  const block = globalsCss
    .slice(rootIdx, end + 1)
    .split("\n")
    .map((line) => (line.startsWith("    ") ? line.slice(2) : line))
    .join("\n");
  return (
    "/* GENERATED by scripts/sync-website-chrome.mjs - DO NOT EDIT.\n" +
    " * Didit design tokens, extracted verbatim from\n" +
    " * fe-didit-website-v4 src/app/globals.css (@layer base :root block).\n" +
    " */\n\n" +
    block +
    "\n"
  );
}

/** Extract the message subtrees one locale's vendored components need. */
export function extractMessages(localeJson, subtrees) {
  const source = JSON.parse(localeJson);
  const out = {};
  for (const dotted of subtrees) {
    const parts = dotted.split(".");
    let node = source;
    for (const p of parts) {
      if (node == null || typeof node !== "object" || !(p in node)) {
        throw new Error(`message subtree missing: ${dotted} (at '${p}')`);
      }
      node = node[p];
    }
    let target = out;
    for (const p of parts.slice(0, -1)) {
      target[p] ??= {};
      target = target[p];
    }
    target[parts[parts.length - 1]] = node;
  }
  return JSON.stringify(out, null, 2) + "\n";
}

/** Compute every vendored artifact's expected content from a source. */
export function computeExpected(manifest, source) {
  const read = makeReader(source);
  const list = makeLister(source);
  const { SYNCED_FILES, TOKENS, MESSAGE_SUBTREES, LOCALES, ASSETS, ASSET_DIRS, VENDOR_DIR } = manifest;
  /** @type {{dest: string, content: Buffer, kind: string, src: string}[]} */
  const artifacts = [];
  for (const f of SYNCED_FILES) {
    const raw = read(f.src);
    const content =
      f.transform === "none" || !/\.(ts|tsx|mjs|cjs)$/.test(f.src)
        ? raw
        : Buffer.from(rewriteImports(raw.toString("utf8")));
    artifacts.push({ dest: path.join(VENDOR_DIR, f.dest), content, kind: "file", src: f.src });
  }
  artifacts.push({
    dest: path.join(VENDOR_DIR, TOKENS.dest),
    content: Buffer.from(extractTokens(read(TOKENS.src).toString("utf8"))),
    kind: "tokens",
    src: TOKENS.src,
  });
  for (const locale of LOCALES) {
    const src = `messages/${locale}.json`;
    artifacts.push({
      dest: path.join(VENDOR_DIR, `messages/${locale}.json`),
      content: Buffer.from(extractMessages(read(src).toString("utf8"), MESSAGE_SUBTREES)),
      kind: "messages",
      src,
    });
  }
  const assetPaths = [...ASSETS, ...ASSET_DIRS.flatMap((d) => list(d))];
  for (const asset of assetPaths) {
    artifacts.push({ dest: asset, content: read(asset), kind: "asset", src: asset });
  }
  return artifacts;
}

/**
 * Guard: every `@website/...` import in the vendored tree must resolve to a
 * synced file or a declared shim, so a website-side refactor that adds a new
 * dependency fails the sync loudly instead of breaking the build later.
 */
export function validateClosure(manifest, repoRoot) {
  const { SYNCED_FILES, SHIMS, VENDOR_DIR } = manifest;
  const known = new Set([...SYNCED_FILES.map((f) => f.dest), ...SHIMS]);
  const problems = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (/\.(ts|tsx)$/.test(entry.name)) {
        const text = fs.readFileSync(p, "utf8");
        for (const m of text.matchAll(/from "@website\/([^"]+)"/g)) {
          const spec = m[1];
          const hit = [spec, `${spec}.ts`, `${spec}.tsx`, `${spec}/index.ts`, `${spec}/index.tsx`].some(
            (c) => known.has(c),
          );
          if (!hit) problems.push(`${p}: unresolved vendored import @website/${spec}`);
        }
        // Relative imports must stay inside the vendor tree.
        for (const m of text.matchAll(/from "(\.\.?\/[^"]+)"/g)) {
          const resolved = path.relative(path.join(repoRoot, VENDOR_DIR), path.resolve(path.dirname(p), m[1]));
          if (resolved.startsWith("..")) problems.push(`${p}: relative import escapes vendor dir: ${m[1]}`);
        }
      }
    }
  };
  walk(path.join(repoRoot, VENDOR_DIR));
  return problems;
}
